<a href="https://colab.research.google.com/github/gemmamay21/introduction-to-datascience/blob/master/Logistic_Reression_for_Absenteeism.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd
import numpy as np

In [0]:
data_preprocessed= pd.read_csv('Absenteeism_preprocessed.csv')

In [3]:
data_preprocessed.head()

Reason_1  Reason_2  Reason_3  ...  Children  Pet  Absenteeism Time in Hours
0         0         0         0  ...         2    1                          4
1         0         0         0  ...         1    0                          0
2         0         0         0  ...         0    0                          2
3         1         0         0  ...         2    0                          4
4         0         0         0  ...         2    1                          2

[5 rows x 15 columns]

In [0]:
##Create the Targets

In [5]:
data_preprocessed['Absenteeism Time in Hours'].median()

3.0

In [0]:
targets = np.where(data_preprocessed['Absenteeism Time in Hours'] > 
                   data_preprocessed['Absenteeism Time in Hours'].median() , 1, 0)

In [7]:
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [0]:
data_preprocessed['Excessive Absenteeism'] = targets

In [9]:
data_preprocessed.head()

Reason_1  Reason_2  ...  Absenteeism Time in Hours  Excessive Absenteeism
0         0         0  ...                          4                      1
1         0         0  ...                          0                      0
2         0         0  ...                          2                      0
3         1         0  ...                          4                      1
4         0         0  ...                          2                      0

[5 rows x 16 columns]

In [0]:
## Comment on the Targets

In [11]:
targets.sum() / targets.shape[0]

0.45571428571428574

In [0]:
data_with_targets = data_preprocessed.drop(['Absenteeism Time in Hours', 'Day of the Week', 
                                            'Daily Work Load Average', 'Distance to Work'], axis = 1)

In [13]:
data_with_targets is data_preprocessed

False

In [14]:
data_with_targets.head()

Reason_1  Reason_2  Reason_3  ...  Children  Pet  Excessive Absenteeism
0         0         0         0  ...         2    1                      1
1         0         0         0  ...         1    0                      0
2         0         0         0  ...         0    0                      0
3         1         0         0  ...         2    0                      1
4         0         0         0  ...         2    1                      0

[5 rows x 12 columns]

In [15]:
data_with_targets.shape

(700, 12)

In [16]:
data_with_targets.iloc[:,0:14]

Reason_1  Reason_2  Reason_3  ...  Children  Pet  Excessive Absenteeism
0           0         0         0  ...         2    1                      1
1           0         0         0  ...         1    0                      0
2           0         0         0  ...         0    0                      0
3           1         0         0  ...         2    0                      1
4           0         0         0  ...         2    1                      0
5           0         0         0  ...         0    0                      0
6           0         0         0  ...         1    4                      1
7           0         0         0  ...         4    0                      1
8           0         0         1  ...         2    0                      1
9           0         0         0  ...         1    1                      1
10          1         0         0  ...         4    0                      1
11          1         0         0  ...         4    0                      1
12          1         0         0  ...         4    0                      1
13          1         0         0  ...         0    0                      0
14          0         0         0  ...         0    0                      1
15          1         0         0  ...         0    0                      1
16          0         0         0  ...         0    0                      0
17          0         0         1  ...         0    0                      1
18          1         0         0  ...         2    2                      1
19          0         0         0  ...         2    1                      0
20          1         0         0  ...         0    0                      1
21          1         0         0  ...         0    0                      0
22          1         0         0  ...         1    4                      1
23          0         0         0  ...         4    0                      1
24          0         0         1  ...         2    1                      1
25          0         0         0  ...         1    4                      1
26          0         0         0  ...         2    1                      0
27          0         0         0  ...         0    0                      1
28          0         0         1  ...         2    1                      1
29          0         0         0  ...         0    0                      0
..        ...       ...       ...  ...       ...  ...                    ...
670         0         0         0  ...         2    0                      1
671         0         0         1  ...         1    2                      1
672         1         0         0  ...         1    0                      0
673         0         0         0  ...         0    0                      0
674         0         0         0  ...         1    1                      1
675         0         0         1  ...         2    2                      0
676         0         0         0  ...         0    0                      0
677         1         0         0  ...         0    0                      0
678         0         0         0  ...         1    0                      1
679         1         0         0  ...         0    0                      0
680         0         0         0  ...         1    1                      0
681         1         0         0  ...         2    2                      1
682         0         0         1  ...         2    1                      1
683         0         0         0  ...         2    2                      1
684         0         0         0  ...         0    0                      0
685         0         0         0  ...         1    0                      0
686         1         0         0  ...         1    0                      0
687         0         0         0  ...         0    0                      0
688         0         0         0  ...         1    0                      0
689         0         0         0  ...         0    0                      0
6

In [17]:
data_with_targets.iloc[:,:-1]

Reason_1  Reason_2  Reason_3  ...  Education  Children  Pet
0           0         0         0  ...          0         2    1
1           0         0         0  ...          0         1    0
2           0         0         0  ...          0         0    0
3           1         0         0  ...          0         2    0
4           0         0         0  ...          0         2    1
5           0         0         0  ...          0         0    0
6           0         0         0  ...          0         1    4
7           0         0         0  ...          0         4    0
8           0         0         1  ...          0         2    0
9           0         0         0  ...          1         1    1
10          1         0         0  ...          0         4    0
11          1         0         0  ...          0         4    0
12          1         0         0  ...          0         4    0
13          1         0         0  ...          0         0    0
14          0         0         0  ...          0         0    0
15          1         0         0  ...          0         0    0
16          0         0         0  ...          0         0    0
17          0         0         1  ...          0         0    0
18          1         0         0  ...          0         2    2
19          0         0         0  ...          0         2    1
20          1         0         0  ...          1         0    0
21          1         0         0  ...          0         0    0
22          1         0         0  ...          0         1    4
23          0         0         0  ...          0         4    0
24          0         0         1  ...          0         2    1
25          0         0         0  ...          0         1    4
26          0         0         0  ...          0         2    1
27          0         0         0  ...          0         0    0
28          0         0         1  ...          0         2    1
29          0         0         0  ...          0         0    0
..        ...       ...       ...  ...        ...       ...  ...
670         0         0         0  ...          0         2    0
671         0         0         1  ...          0         1    2
672         1         0         0  ...          0         1    0
673         0         0         0  ...          1         0    0
674         0         0         0  ...          1         1    1
675         0         0         1  ...          1         2    2
676         0         0         0  ...          1         0    0
677         1         0         0  ...          0         0    0
678         0         0         0  ...          0         1    0
679         1         0         0  ...          1         0    0
680         0         0         0  ...          0         1    1
681         1         0         0  ...          1         2    2
682         0         0         1  ...          0         2    1
683         0         0         0  ...          1         2    2
684         0         0         0  ...          1         0    0
685         0         0         0  ...          0         1    0
686         1         0         0  ...          0         1    0
687         0         0         0  ...          0         0    0
688         0         0         0  ...          0         1    0
689         0         0         0  ...          1         0    0
690         0         0         0  ...          0         2    4
691         0         1         0  ...          1         2    0
692         1         0         0  ...          0         2    0
693         1         0         0  ...          1         0    0
694         0         0         0  ...          0         1    1
695         1         0         0  ...          1         2    0
696         1         0         0  ...          0         1    2
697         1         0         0  ...          1         0    0
698         0         0         0  ...          1         0    0
699         0         0         0  ...  

In [0]:
unscaled_inputs = data_with_targets.iloc[:,:-1]

In [0]:
## Standardise the Data

In [0]:
#from sklearn.preprocessing import StandardScaler

#absenteeism_scaler = StandardScaler()

In [0]:
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.preprocessing import StandardScaler

class CustomScaler(BaseEstimator, TransformerMixin):
  
  def __init__ (self, columns,copy=True, with_mean=True, with_std=True):
      self.scaler=StandardScaler(copy,with_mean,with_std)
      self.columns= columns
      self.mean_ = None
      self.var_= None 
    
  def fit(self, X, y=None):
      self.scaler.fit(X[self.columns], y)
      self.mean_=np.mean(X[self.columns])
      self.var_=np.var(X[self.columns])
      return self

  def transform (self, X, y=None, copy=None):
      init_col_order = X.columns
      X_scaled = pd.DataFrame(self.scaler.transform(X[self.columns]), columns=self.columns)
      X_not_scaled = X.loc[:, ~X.columns.isin(self.columns)]
      return pd.concat([X_not_scaled, X_scaled], axis=1)[init_col_order]


In [22]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pet'], dtype=object)

In [0]:
#columns_to_scale = ['Month Value','Day of the Week', 'Transportation Expense', 'Distance to Work',
       #'Age', 'Daily Work Load Average', 'Body Mass Index', 'Education','Children', 'Pet']
  
  columns_to_omit = ['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Education']

In [0]:
columns_to_scale = [x for x in unscaled_inputs.columns.values if x not in columns_to_omit]

In [0]:
absenteeism_scaler = CustomScaler(columns_to_scale)

In [26]:
absenteeism_scaler.fit(unscaled_inputs)

CustomScaler(columns=['Month Value', 'Transportation Expense', 'Age',
                      'Body Mass Index', 'Children', 'Pet'],
             copy=None, with_mean=None, with_std=None)

In [0]:
scaled_inputs = absenteeism_scaler.transform(unscaled_inputs)

In [28]:
scaled_inputs

Reason_1  Reason_2  Reason_3  ...  Education  Children       Pet
0           0         0         0  ...          0  0.880469  0.268487
1           0         0         0  ...          0 -0.019280 -0.589690
2           0         0         0  ...          0 -0.919030 -0.589690
3           1         0         0  ...          0  0.880469 -0.589690
4           0         0         0  ...          0  0.880469  0.268487
5           0         0         0  ...          0 -0.919030 -0.589690
6           0         0         0  ...          0 -0.019280  2.843016
7           0         0         0  ...          0  2.679969 -0.589690
8           0         0         1  ...          0  0.880469 -0.589690
9           0         0         0  ...          1 -0.019280  0.268487
10          1         0         0  ...          0  2.679969 -0.589690
11          1         0         0  ...          0  2.679969 -0.589690
12          1         0         0  ...          0  2.679969 -0.589690
13          1         0         0  ...          0 -0.919030 -0.589690
14          0         0         0  ...          0 -0.919030 -0.589690
15          1         0         0  ...          0 -0.919030 -0.589690
16          0         0         0  ...          0 -0.919030 -0.589690
17          0         0         1  ...          0 -0.919030 -0.589690
18          1         0         0  ...          0  0.880469  1.126663
19          0         0         0  ...          0  0.880469  0.268487
20          1         0         0  ...          1 -0.919030 -0.589690
21          1         0         0  ...          0 -0.919030 -0.589690
22          1         0         0  ...          0 -0.019280  2.843016
23          0         0         0  ...          0  2.679969 -0.589690
24          0         0         1  ...          0  0.880469  0.268487
25          0         0         0  ...          0 -0.019280  2.843016
26          0         0         0  ...          0  0.880469  0.268487
27          0         0         0  ...          0 -0.919030 -0.589690
28          0         0         1  ...          0  0.880469  0.268487
29          0         0         0  ...          0 -0.919030 -0.589690
..        ...       ...       ...  ...        ...       ...       ...
670         0         0         0  ...          0  0.880469 -0.589690
671         0         0         1  ...          0 -0.019280  1.126663
672         1         0         0  ...          0 -0.019280 -0.589690
673         0         0         0  ...          1 -0.919030 -0.589690
674         0         0         0  ...          1 -0.019280  0.268487
675         0         0         1  ...          1  0.880469  1.126663
676         0         0         0  ...          1 -0.919030 -0.589690
677         1         0         0  ...          0 -0.919030 -0.589690
678         0         0         0  ...          0 -0.019280 -0.589690
679         1         0         0  ...          1 -0.919030 -0.589690
680         0         0         0  ...          0 -0.019280  0.268487
681         1         0         0  ...          1  0.880469  1.126663
682         0         0         1  ...          0  0.880469  0.268487
683         0         0         0  ...          1  0.880469  1.126663
684         0         0         0  ...          1 -0.919030 -0.589690
685         0         0         0  ...          0 -0.019280 -0.589690
686         1         0         0  ...          0 -0.019280 -0.589690
687         0         0         0  ...          0 -0.919030 -0.589690
688         0         0         0  ...          0 -0.019280 -0.589690
689         0         0         0  ...          1 -0.919030 -0.589690
690         0         0         0  ...          0  0.880469  2.843016
691         0         1         0  ...          1  0.880469 -0.589690
692         1         0         0  ...          0  0.880469 -0.589690
693         1         0         0  ...          1 -0.919030 -0.589690
694         0         0         0  ...          0 -0.019280  0.268487
695         1  

In [29]:
scaled_inputs.shape


(700, 11)

In [0]:
from sklearn.model_selection import train_test_split

In [31]:
train_test_split(scaled_inputs, targets)

[     Reason_1  Reason_2  Reason_3  ...  Education  Children       Pet
 309         0         0         0  ...          0 -0.019280 -0.589690
 441         0         0         0  ...          0 -0.919030 -0.589690
 218         1         0         0  ...          0 -0.019280 -0.589690
 395         0         0         0  ...          1 -0.019280  0.268487
 67          0         0         0  ...          0 -0.019280  1.126663
 342         0         0         0  ...          1 -0.019280  0.268487
 631         0         0         0  ...          0 -0.919030 -0.589690
 288         1         0         0  ...          0 -0.919030 -0.589690
 17          0         0         1  ...          0 -0.919030 -0.589690
 566         0         0         0  ...          0 -0.019280  1.126663
 581         0         0         0  ...          0 -0.919030 -0.589690
 95          0         0         0  ...          0 -0.019280  1.126663
 386         0         0         0  ...          0 -0.919030 -0.589690
 368  

In [0]:
x_train, x_test, y_train, y_test = train_test_split(scaled_inputs, targets, train_size = 0.8, random_state = 20)

In [33]:
print(x_train.shape, y_train.shape)

(560, 11) (560,)


In [34]:
print (x_test.shape, y_test.shape)

(140, 11) (140,)


In [0]:
##Logistic Regression with Sklean

In [0]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

In [0]:
##Training the Model

In [0]:
reg = LogisticRegression()

In [39]:
reg.fit(x_train, y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [40]:
reg.score(x_train, y_train)

0.775

In [0]:
##Manually Check the Accuracy

In [42]:
model_outputs = reg.predict(x_train)
model_outputs

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,

In [43]:
y_train

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,

In [44]:
model_outputs == y_train

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True, False, False,  True,  True,  True,  True,
       False,  True, False,  True, False, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False,  True,  True,  True,  True, False,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True, False,  True,  True, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
       False,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,

In [45]:
np.sum((model_outputs==y_train))

434

In [46]:
model_outputs.shape[0]

560

In [47]:
np.sum((model_outputs == y_train)) / model_outputs.shape[0]

0.775

In [48]:
reg.intercept_

array([-1.43138127])

In [49]:
reg.coef_

array([[ 2.60237227,  0.84350002,  2.94078723,  0.63723433,  0.00565051,
         0.61953401, -0.17635497,  0.28410321, -0.26372527,  0.35195032,
        -0.27369766]])

In [50]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pet'], dtype=object)

In [0]:
feature_name = unscaled_inputs.columns.values

In [52]:
summary_table = pd.DataFrame (columns=['Feature Name'], data = feature_name)
summary_table ['Coefficient'] = np.transpose (reg.coef_)
summary_table

Feature Name  Coefficient
0                 Reason_1     2.602372
1                 Reason_2     0.843500
2                 Reason_3     2.940787
3                 Reason_4     0.637234
4              Month Value     0.005651
5   Transportation Expense     0.619534
6                      Age    -0.176355
7          Body Mass Index     0.284103
8                Education    -0.263725
9                 Children     0.351950
10                     Pet    -0.273698

In [53]:
summary_table.index = summary_table.index + 1
summary_table.loc[0] = ['Intercept', reg.intercept_[0]]
summary_table

Feature Name  Coefficient
1                 Reason_1     2.602372
2                 Reason_2     0.843500
3                 Reason_3     2.940787
4                 Reason_4     0.637234
5              Month Value     0.005651
6   Transportation Expense     0.619534
7                      Age    -0.176355
8          Body Mass Index     0.284103
9                Education    -0.263725
10                Children     0.351950
11                     Pet    -0.273698
0                Intercept    -1.431381

In [0]:
##Interpretting the Coefficients

In [0]:
summary_table['Odds_ratio'] = np.exp(summary_table.Coefficient)

In [56]:
summary_table

Feature Name  Coefficient  Odds_ratio
1                 Reason_1     2.602372   13.495716
2                 Reason_2     0.843500    2.324489
3                 Reason_3     2.940787   18.930743
4                 Reason_4     0.637234    1.891243
5              Month Value     0.005651    1.005667
6   Transportation Expense     0.619534    1.858062
7                      Age    -0.176355    0.838320
8          Body Mass Index     0.284103    1.328570
9                Education    -0.263725    0.768185
10                Children     0.351950    1.421838
11                     Pet    -0.273698    0.760562
0                Intercept    -1.431381    0.238979

In [57]:
summary_table.sort_values('Odds_ratio', ascending=False)

Feature Name  Coefficient  Odds_ratio
3                 Reason_3     2.940787   18.930743
1                 Reason_1     2.602372   13.495716
2                 Reason_2     0.843500    2.324489
4                 Reason_4     0.637234    1.891243
6   Transportation Expense     0.619534    1.858062
10                Children     0.351950    1.421838
8          Body Mass Index     0.284103    1.328570
5              Month Value     0.005651    1.005667
7                      Age    -0.176355    0.838320
9                Education    -0.263725    0.768185
11                     Pet    -0.273698    0.760562
0                Intercept    -1.431381    0.238979

In [58]:
reg.score(x_test, y_test)

0.7357142857142858

In [59]:
predicted_proba = reg.predict_proba(x_test)
predicted_proba

array([[0.75308922, 0.24691078],
       [0.60926091, 0.39073909],
       [0.4859575 , 0.5140425 ],
       [0.7552847 , 0.2447153 ],
       [0.0839675 , 0.9160325 ],
       [0.30192695, 0.69807305],
       [0.30166774, 0.69833226],
       [0.1151045 , 0.8848955 ],
       [0.73775967, 0.26224033],
       [0.75403176, 0.24596824],
       [0.50719215, 0.49280785],
       [0.19719276, 0.80280724],
       [0.06163196, 0.93836804],
       [0.70917025, 0.29082975],
       [0.29280547, 0.70719453],
       [0.5241047 , 0.4758953 ],
       [0.50676929, 0.49323071],
       [0.50888352, 0.49111648],
       [0.367008  , 0.632992  ],
       [0.06355661, 0.93644339],
       [0.73644831, 0.26355169],
       [0.7552847 , 0.2447153 ],
       [0.47457156, 0.52542844],
       [0.47288443, 0.52711557],
       [0.22026535, 0.77973465],
       [0.73808685, 0.26191315],
       [0.51184512, 0.48815488],
       [0.87683579, 0.12316421],
       [0.23445563, 0.76554437],
       [0.7552847 , 0.2447153 ],
       [0.

In [60]:
predicted_proba.shape

(140, 2)

In [61]:
predicted_proba[:,1]

array([0.24691078, 0.39073909, 0.5140425 , 0.2447153 , 0.9160325 ,
       0.69807305, 0.69833226, 0.8848955 , 0.26224033, 0.24596824,
       0.49280785, 0.80280724, 0.93836804, 0.29082975, 0.70719453,
       0.4758953 , 0.49323071, 0.49111648, 0.632992  , 0.93644339,
       0.26355169, 0.2447153 , 0.52542844, 0.52711557, 0.77973465,
       0.26191315, 0.48815488, 0.12316421, 0.76554437, 0.2447153 ,
       0.38912926, 0.71585927, 0.70056321, 0.49365359, 0.2447153 ,
       0.59546518, 0.26256777, 0.78560289, 0.43689507, 0.60455576,
       0.24440274, 0.49889237, 0.26125957, 0.44701216, 0.80689602,
       0.60831063, 0.72248525, 0.24534123, 0.24855634, 0.24409045,
       0.50227596, 0.32586203, 0.69807305, 0.24697976, 0.82067559,
       0.39154489, 0.90719507, 0.26697852, 0.35791316, 0.35830205,
       0.70399998, 0.6991417 , 0.26797295, 0.78118404, 0.24619646,
       0.24659633, 0.09025875, 0.26289548, 0.7674276 , 0.29222745,
       0.26060705, 0.35283656, 0.88319236, 0.43606282, 0.59383

In [0]:
##Save the Model

In [0]:
import pickle

In [0]:
with open('model','wb') as file:
  pickle.dump(reg, file)

In [0]:
with open('scaler', 'wb') as file:
  pickle.dump(absenteeism_scaler, file)